### ISSUE TITLE
Export: Set default values on export form (including for Spanish)

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/pelican-frontend#32]
Once the templates become established, the user experience would be better if users could select a template by name from a dropdown list rather than providing a URL/ID.

his should also lead to fewer errors when creating a report.

**Comment by jpmckinney** [comment]
The app has default document IDs stored in settings, so we can also pre-populate the fields with those IDs (and add a setting for the default folder ID).

Since the form has language radio buttons, we could similarly add settings for Spanish IDs, and change the pre-populated fields if the user changes language (can move language to top of form).

That way, the user doesn't need to enter any data other than the optional document title.

**Comment by jpmckinney** [comment]
Re-opening as this is not solved for Spanish.
