### ISSUE TITLE
Report failures <1%

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/pelican-frontend#38]
For example, the 'procuring entity organization reference' check reports no failures on the compiled release screen:

![image](https://user-images.githubusercontent.com/19265814/76175880-741a4200-6213-11ea-8dfb-517db6b6565e.png)

But clicking through to the check shows that there are actually 3 failures:

![image](https://user-images.githubusercontent.com/19265814/76175903-8d22f300-6213-11ea-9db1-5ed358f84a3c.png)

Similarly, on the field checks screen, if the failure rate is <1% the check reports 100% success.

**Comment by jpmckinney** [comment]
https://dqt.datlab.eu/resource/352

I'd expect that, when it's exactly 0%, that it's the same grey in any column, not just the middle column.

![Screen Shot 2021-10-01 at 8 07 32 PM](https://user-images.githubusercontent.com/26463/135697222-1ba5de71-dc8f-4b94-8a6c-bcffd35793be.png)

**Comment by jakubkrafka** [comment]
Well, you originally asked for "... that were exactly zero be a very light grey.":) I'm not trying to "catch you", just double-checking here, as the original idea seems to work nicely here. The zero here is just a "placeholder", to ease the UX, not to transfer any info.

**Comment by jpmckinney** [comment]
There were 3 requests:

1. Use ">0%" and "<100%" if not exactly 0 or exactly 100, because it is relevant to users to know when there are exceptional passes/failures. This was done.
2. Put a "0%" instead of an empty cell, to make the table easier to read (i.e. it is clearer that there are no passes/failures if they read "0%"). This was done.
3. Make all "0%" grey, so that it is easier to ignore them and see the more relevant non-zero values. This was only done for the failure column, for some reason?
