### ISSUE TITLE
Document the meaning of metadata fields displayed in 'sample of failures' preview

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/pelican-frontend#43]
I'm not sure how to interpret some of the metadata fields in the example below.

I don't know what `version` is in relation to and I can take a guess at `value`, `result`, `pass_count` and `application_count` but it would be good to have them documented.

The documentation (or a link to it) should be proximate to where the fields appear in the interface.

![image](https://user-images.githubusercontent.com/19265814/76174116-29e09300-620a-11ea-92bb-bb82fa2b27fa.png)

**Comment by jpmckinney** [comment]
Noting that I wrote some descriptions for developers at https://pelican-backend.readthedocs.io/en/latest/tasks/checks/compiled-release.html

The meta keys should be standardized before being documented (open-contracting/pelican-backend#76).

**Comment by jpmckinney** [comment]
I think https://github.com/open-contracting/pelican-frontend/issues/49 and https://github.com/open-contracting/pelican-frontend/issues/50 are better solutions to this, as their goal is to render this raw information in an intelligible way, and require less effort from the user (no need to click on a sample first). 

I improved the naming of the meta keys for clarity, as part of https://github.com/open-contracting/pelican-backend/issues/76

Otherwise, for now, I added a documentation page (not linked from the UI). The keys are either clear, or can be learned once.
